server:
  port: 3344

spring:
  application:
    name:  icodecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:summerpunch/icodecloud-config.git #GitHub上面的git仓库名字


